services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Register resource models as tagged services (without autowiring)
    AlexFigures\Symfony\Tests\Fixtures\Model\Article:
        autowire: false
        tags:
            - { name: 'jsonapi.resource', type: 'articles' }

    AlexFigures\Symfony\Tests\Fixtures\Model\Author:
        autowire: false
        tags:
            - { name: 'jsonapi.resource', type: 'authors' }

    AlexFigures\Symfony\Tests\Fixtures\Model\Tag:
        autowire: false
        tags:
            - { name: 'jsonapi.resource', type: 'tags' }

    # Repository with large dataset
    AlexFigures\Symfony\StressApp\StressInMemoryRepository:
        arguments:
            $registry: '@AlexFigures\Symfony\Resource\Registry\ResourceRegistryInterface'
        public: true

    # Alias for ResourceRepository contract
    AlexFigures\Symfony\Contract\Data\ResourceRepository:
        alias: AlexFigures\Symfony\StressApp\StressInMemoryRepository
        public: true

    # Processor (note: InMemoryPersister implements the old ResourcePersister interface,
    # but it's compatible with ResourceProcessor since they have the same method signatures)
    AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryPersister:
        arguments:
            $repository: '@AlexFigures\Symfony\StressApp\StressInMemoryRepository'
            $registry: '@AlexFigures\Symfony\Resource\Registry\ResourceRegistryInterface'
            $transactionManager: '@AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryTransactionManager'
        public: true

    AlexFigures\Symfony\Contract\Data\ResourceProcessor:
        alias: AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryPersister
        public: true

    # Transaction Manager
    AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryTransactionManager:
        public: true

    AlexFigures\Symfony\Contract\Tx\TransactionManager:
        alias: AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryTransactionManager
        public: true

    # Relationship services
    AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryRelationshipReader:
        arguments:
            $repository: '@AlexFigures\Symfony\StressApp\StressInMemoryRepository'
            $registry: '@AlexFigures\Symfony\Resource\Registry\ResourceRegistryInterface'
        public: true

    AlexFigures\Symfony\Contract\Data\RelationshipReader:
        alias: AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryRelationshipReader
        public: true

    AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryRelationshipUpdater:
        arguments:
            $repository: '@AlexFigures\Symfony\StressApp\StressInMemoryRepository'
            $registry: '@AlexFigures\Symfony\Resource\Registry\ResourceRegistryInterface'
        public: true

    AlexFigures\Symfony\Contract\Data\RelationshipUpdater:
        alias: AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryRelationshipUpdater
        public: true

    # Existence Checker
    AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryExistenceChecker:
        arguments:
            $repository: '@AlexFigures\Symfony\StressApp\StressInMemoryRepository'
        public: true

    AlexFigures\Symfony\Contract\Data\ExistenceChecker:
        alias: AlexFigures\Symfony\Tests\Fixtures\InMemory\InMemoryExistenceChecker
        public: true

parameters:
    jsonapi.strict_content_negotiation: false
    jsonapi.media_type: 'application/vnd.api+json'
    jsonapi.limits:
        max_include_depth: 3
        max_page_size: 100
        complexity_budget: 1000

