<?php

declare(strict_types=1);

namespace AlexFigures\Symfony\Tests\Integration\Fixtures\Entity;

use AlexFigures\Symfony\Resource\Attribute\Attribute;
use AlexFigures\Symfony\Resource\Attribute\Id;
use AlexFigures\Symfony\Resource\Attribute\JsonApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Test entity with integer primary key and database-generated sequence.
 *
 * This entity demonstrates that the JSON:API implementation correctly handles
 * entities with integer IDs generated by database sequences, as opposed to
 * application-generated UUIDs.
 */
#[ORM\Entity]
#[ORM\Table(name: 'comments')]
#[JsonApiResource(
    type: 'comments',
    normalizationContext: ['groups' => ['comment:read']],
    denormalizationContext: ['groups' => ['comment:write']],
)]
class Comment
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'SEQUENCE')]
    #[ORM\SequenceGenerator(sequenceName: 'comments_id_seq', allocationSize: 1, initialValue: 1)]
    #[Id]
    #[Attribute]
    #[Groups(['comment:read'])]
    private ?int $id = null;

    #[ORM\Column(type: 'text')]
    #[Attribute]
    #[Groups(['comment:read', 'comment:write'])]
    private string $content;

    #[ORM\Column(type: 'string', length: 255)]
    #[Attribute]
    #[Groups(['comment:read', 'comment:write'])]
    private string $authorName;

    #[ORM\Column(type: 'integer')]
    #[Attribute]
    #[Groups(['comment:read', 'comment:write'])]
    private int $rating;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;
        return $this;
    }

    public function getAuthorName(): string
    {
        return $this->authorName;
    }

    public function setAuthorName(string $authorName): self
    {
        $this->authorName = $authorName;
        return $this;
    }

    public function getRating(): int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;
        return $this;
    }
}
