name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [ main ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          publish_results: true

      - name: Upload Scorecard results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
